[launcher]
background                = "#0F1E14"
background-alpha          = 0.95
text                      = "#B8ECC6"
border                    = "hyprland.active-border-foreground"
border-alpha              = 1.0
scrim                     = "#000200"
scrim-alpha               = 0.5
selected-background       = "#00FF41"
selected-background-alpha = 0.12
selected-text             = "#DFFFE9"
selected-border           = "hyprland.active-border-foreground"
selected-border-alpha     = 0.35
