[launcher]
background                = "#121C13"
background-alpha          = 0.95
text                      = "#ACD2B4"
border                    = "hyprland.active-border-foreground"
border-alpha              = 1.0
scrim                     = "#040604"
scrim-alpha               = 0.5
selected-background       = "#60C76B"
selected-background-alpha = 0.12
selected-text             = "#D4EDD9"
selected-border           = "hyprland.active-border-foreground"
selected-border-alpha     = 0.35
